version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./ssale/Dockerfile
    volumes:
      - ./backend:/app/backend
    stdin_open: true
    tty: true
    command: uvicorn ssale.asgi:application --host 0.0.0.0 --port 80
    ports:
      - 80:80
  frontend:
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
    ports:
      - 3000:3000
    # environment:
    #   - NODE_ENV=development
    depends_on:
      - backend
    command: yarn dev