# Generated by Django 4.2.5 on 2023-12-19 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='agent.chatsession'),
        ),
    ]
