# Generated by Django 4.2.5 on 2023-12-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
