# Generated by Django 4.2.5 on 2023-12-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_chatsession_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='data',
            field=models.TextField(default='[]'),
        ),
    ]
